mysql_root_password: "secure_root_password"
mysql_wordpress_db: "wordpress_db"
mysql_wordpress_user: "wordpress_user"
mysql_wordpress_password: "secure_wp_password"
wordpress_url: "https://wordpress.org/latest.tar.gz"
wordpress_dir: "/var/www/html/wordpress"
server_admin_email: "admin@example.com"
nginx_conf : "your_domain.conf"
nginx_host : "your_domain"
nginx_port: "80"
php_version : "php8.3"
