mysql_root_password: "secure_root_password"
mysql_wordpress_db: "wordpress_db"
mysql_wordpress_user: "wordpress_user"
wordpress_url: "https://wordpress.org/latest.tar.gz"
wordpress_dir: "/var/www/html/wordpress"
server_admin_email: "admin@example.com"
nginx_conf : "wordpress"
