---
- name: Install Nginx
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nginx

- name: Set Nginx conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_conf }}"
    mode: "0755"


- name: Enable new site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_conf }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_conf }}"
    state: link
  notify: reload nginx

- name: Remove default site
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload nginx
