- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Enable Apache modules
  command: a2enmod rewrite
  notify: restart apache

- name: Set up Apache VirtualHost
  copy:
    dest: /etc/apache2/sites-available/wordpress.conf
    content: |
      <VirtualHost *:80>
          ServerAdmin {{ server_admin_email }}
          DocumentRoot {{ wordpress_dir }}
          <Directory {{ wordpress_dir }}>
              AllowOverride All
          </Directory>
      </VirtualHost>

- name: Enable WordPress site
  command: a2ensite wordpress
  notify: restart apache

- name: Disable default site
  command: a2dissite 000-default
  notify: restart apache

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
