---
- name: Install mysql
  hosts: localhost
  become: true
  vars:
    mysql_root_password: "secure_root_password"
    mysql_wordpress_db: "wordpress_db"
    mysql_wordpress_user: "wordpress_user"
    mysql_wordpress_password: "secure_wp_password"
    wordpress_url: "https://wordpress.org/latest.tar.gz"
    wordpress_dir: "/var/www/html/wordpress"
    server_admin_email: "admin@example.com"
  tasks:
    - name: Install MySQL
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - mysql-server
        - python3-pymysql

    - name: Create WordPress database
      mysql_db:
        name: "{{ mysql_wordpress_db }}"
        state: present
        
    
    - name: Create WordPress database user
      mysql_user:
        name: "{{ mysql_wordpress_user }}"
        password: "{{ mysql_wordpress_password }}"
        priv: "{{ mysql_wordpress_db }}.*:ALL"
        state: present
