- name: latest.tar.gz File exit or not
  ansible.builtin.stat:
    path: /tmp/latest.tar.gz
  register: st

- name: Download WordPress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/latest.tar.gz
  when: st.state.islnk is not defined

- name: Extract WordPress
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Set permissions
  file:
    path: "{{ wordpress_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: yes

- name: Create wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_dir }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: "0644"
