- name: Latest.tar.gz File exit or not
  ansible.builtin.stat:
    path: /tmp/latest.tar.gz
  register: st

- name: Download WordPress
  ansible.builtin.get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/latest.tar.gz
    mode: "0755"
  when: st.stat.exists is not defined or not st.stat.exists

- name: Check if WordPress is already extracted
  ansible.builtin.stat:
    path: "{{ wordpress_dir }}/wp-config-sample.php"
  register: wp_extracted

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/html/
    remote_src:
  when: not wp_extracted.stat.exists

- name: Set permissions
  ansible.builtin.file:
    path: "{{ wordpress_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: true

- name: Create wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wordpress_dir }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'
