- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server
    - python3-mysqldb

- name: Create WordPress database
  mysql_db:
    name: "{{ mysql_wordpress_db }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ mysql_wordpress_user }}"
    password: "{{ mysql_wordpress_password }}"
    priv: "{{ mysql_wordpress_db }}.*:ALL"
    state: present
