- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server
    - python3-pymysql

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Create WordPress database
  mysql_db:
    name: "{{ mysql_wordpress_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    

- name: Create WordPress database user
  mysql_user:
    name: "{{ mysql_wordpress_user }}"
    password: "{{ mysql_wordpress_password }}"
    priv: "{{ mysql_wordpress_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
