- name: Install MySQL
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mysql-server
    - python3-pymysql

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ mysql_wordpress_db }}"
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ mysql_wordpress_user }}"
    password: "{{ mysql_wordpress_password }}"
    priv: "{{ mysql_wordpress_db }}.*:ALL"
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
