---
- name: Add PHP repo
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP and extensions
  ansible.builtin.apt:
    name: "php{{ php_version }}"
    state: present
    update_cache: true

- name: Install PHP and extensions
  ansible.builtin.apt:
    name: "php{{ php_version }}-{{ item }}"
    state: present
    update_cache: true
  with_items:
    - "bcmath"
    - "cli"
    - "common"
    - "curl"
    - "fpm"
    - "gd"
    - "intl"
    - "imagick"
    - "mbstring"
    - "mysql"
    - "xml"
    - "zip"

- name: Set PHP upload max filesize
  ansible.builtin.lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 50M"
    state: present
  notify: reload php

- name: Set PHP post max filesize
  ansible.builtin.lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 50M"
    state: present
  notify: reload php
